version: '3.1'

services:

  mariadb:
    image: mariadb:10.2
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 0.0.0.0:3309:3306
